### PR TITLE
40395 Multiple forms with reCAPTCHA lead to wrong submission

### PR DESCRIPTION
**Pull request by dai-eastgate**
related to https://github.com/onOffice-Web-Org/oo-wp-plugin/issues/631

changed log :
Update multiple forms with reCAPTCHA

### CODE REVIEW

**Comment by andernath** [comment]
@yeneastgate could you please merge master into this branch?

**Comment by yeneastgate** [comment]
> @yeneastgate could you please resolve conflicts and merge master into this branch?

I have merged and test it again. However, there are some problems I need to check. I will get back to you asap. Thanks.

**Comment by yeneastgate** [comment]
@andernath I have fixed it and tested it again. Please help us to review. Thanks!

https://files.fm/u/g266zjjpny

**Comment by yeneastgate** [comment]
@andernath @fredericalpers I have fixed and tested this PR. Please help us to review. Thanks!
Here is a video demo: https://files.fm/f/scgt9zhdnz

**Review by andernath — APPROVED** [review]
I will start testing

**Comment by andernath** [comment]
@dai-eastgate and @yeneastgate 
Test looks good!
But I found a bug, which seems to be connected with recapcha loading. 
I created a Issue for 4.16: #669

**Pull request merged**
