### PR TITLE
42676 Search field for field lists

### PR DESCRIPTION
**Pull request by dai-eastgate**
related to https://github.com/onOffice-Web-Org/oo-wp-plugin/issues/674
changed log:
Add search field for field lists

### CODE REVIEW

**Comment by dai-eastgate** [comment]
@andernath I have refactored the code. Please help us to review again. Thanks!

**Review by andernath — DISMISSED** [review]

**Review by andernath — COMMENTED** [review]
Sorry found some more code smells, could you please take a look?
Found a Issue while testing:
If I press enter in input search field the page will reload and save. Could you prevent this action?

**Comment by andernath** [comment]
@dai-eastgate sorry i forgot one thing: you implemented serveral createSearchFieldForFieldLists funtions but only one TestClassFormModelBuilderDBForm.php was updated. What about TestClassFormModelBuilderDBEstateListSettings, TestClassFormModelBuilderDBAddress end so on?

**Comment by dai-eastgate** [comment]
> @dai-eastgate sorry i forgot one thing: you implemented serveral createSearchFieldForFieldLists funtions but only one TestClassFormModelBuilderDBForm.php was updated. What about TestClassFormModelBuilderDBEstateListSettings, TestClassFormModelBuilderDBAddress and maybe others?

@andernath Currently, TestClassFormModelBuilderDBEstateListSettings and TestClassFormModelBuilderDBAddress are directly instantiating classes without using a container. I will need additional time to revise all related unit tests and retest them.

**Comment by dai-eastgate** [comment]
@andernath I have refactored the code, please review it again. Thanks!

**Review by andernath — APPROVED** [review]

**Pull request merged**
