### PR TITLE
38334 Only load required scripts and CSS

### PR DESCRIPTION
**Pull request by dai-eastgate**
related to https://github.com/onOffice-Web-Org/oo-wp-plugin/issues/554

changed log :
Update load the js file in the right place

### CODE REVIEW

**Comment by andernath** [comment]
@yeneastgate or @dai-eastgate could you merge master into this bracne. I think it will show some merge conflicts.

**Comment by dai-eastgate** [comment]
> @yeneastgate or @dai-eastgate could you merge master into this bracne. I think it will show some merge conflicts.

I will merge master into this branch.

**Review by andernath — APPROVED** [review]
I will start testing.

**Comment by dai-eastgate** [comment]
> While testing I get a TypeError: $ is not a function. I don't know why this happens on my W3PM test enviorement. Because Jquery works well on another onOffice-Demo enviorement.
> 
> Error on Estatelist with multi select fields in search: https://w3pm.onofficeweb.com/
> 
> No Error on Estatelist with multi select fields in search: https://wp-plugin-demo.onoffice.com/en/estates/estate-list/
> 
> I double check right pluginversion -> both Version 4.14-18-gc61278ec) ✔ I checked settings in Estatelists -> nearly similar (default template...)
> 
> Maybe you habe an idea? @dai-eastgate @yeneastgate ?

@andernath I will check it. Thanks!

**Review by andernath — APPROVED** [review]
Repeat testing.

**Comment by andernath** [comment]
@dai-eastgate 
Maybe you forget to implement loading leaflet, only if maps are in use, See your comment here https://github.com/onOffice-Web-Org/oo-wp-plugin/issues/574#issuecomment-1663387758

**Comment by dai-eastgate** [comment]
> @dai-eastgate Maybe you forget to implement loading leaflet, only if maps are in use, See your comment here [#574 (comment)](https://github.com/onOffice-Web-Org/oo-wp-plugin/issues/574#issuecomment-1663387758)

I will check it. Thanks!

**Comment by andernath** [comment]
> > @dai-eastgate Maybe you forget to implement loading leaflet, only if maps are in use, See your comment here [#574 (comment)](https://github.com/onOffice-Web-Org/oo-wp-plugin/issues/574#issuecomment-1663387758)
> 
> I will check it. Thanks!

@dai-eastgate will you implement leaflet loading or is it part of another issue?

**Comment by dai-eastgate** [comment]
> 
> @dai-eastgate will you implement leaflet loading or is it part of another issue?

I am currently implementing and testing it. I will update you with the results by the end of today.

**Comment by andernath** [comment]
> > @dai-eastgate will you implement leaflet loading or is it part of another issue?
> 
> @andernath I'm implementing "leaflet loading". I will respond to you by the end of today. Because this feature works a bit differently, I had to check it more carefully

Good Job! Thank you :)

**Comment by dai-eastgate** [comment]
@andernath I have found a solution that loads the "leaflet" library only when needed and puts it in branch "38334-only-load-required-scripts-and-css-v2". 

https://github.com/onOffice-Web-Org/oo-wp-plugin/assets/106214469/a8f932d4-1d54-4078-917e-619753b88160


However, this solution will affect backward compatibility.
Because I need to edit the logic code in the "map-osm.php" template file.
=> Do you agree to implement this solution?

In my personal opinion, I suggest keeping the "leaflet" library loaded in the <head> tag and loading it every time like the current master branch.

**Comment by yeneastgate** [comment]
> I see your struggle :/
> And I agree with you.
> Lets discard the changes in "38334-only-load-required-scripts-and-css-v2" and keep loading leaflet always.

**Comment by dai-eastgate** [comment]
> And I agree with you.
> Lets discard the changes in "38334-only-load-required-scripts-and-css-v2" and keep loading leaflet always.

@andernath OK, thanks. I will keep loading leaflet always

**Comment by dai-eastgate** [comment]
> Can I continue testing here in #610 or did I miss any changes on "38334-only-load-required-scripts-and-css-v2" wich needed to be merged in here?

@andernath I updated the code in #610. Please review it again. Thanks

**Review by andernath — APPROVED** [review]
Start Testing

**Pull request merged**
