### PR TITLE
43301 Hot fix jquery id selector duplicated saved notification

### PR DESCRIPTION
**Pull request by dai-eastgate**
related to https://github.com/onOffice-Web-Org/oo-wp-plugin/issues/697
changed log:
Fix jquery id selector duplicated

### CODE REVIEW

**Comment by dai-eastgate** [comment]
@fredericalpers @andernath We have found an issue related to issue #697.
Some other plugins(ex: yoast seo,..) also use the ID "#poststuff".
image
Therefore, we replace the "#poststuff" id with "oo-poststuff" class of jQuery selector to avoid conflict feature.

Please check and release it soon.

**Review by andernath — APPROVED** [review]

**Comment by andernath** [comment]
@dai-eastgate Thanks for fixing. I found some more issues and merged your changes in my branch https://github.com/onOffice-Web-Org/oo-wp-plugin/pull/831

**Comment by dai-eastgate** [comment]
> @dai-eastgate Thanks for fixing. I found some more issues and merged your changes in my branch #831

@andernath Thanks for letting me know. I'll take note and be more thorough next time.

**Comment by andernath** [comment]
I will close PR, because these changes already merged into master with https://github.com/onOffice-Web-Org/oo-wp-plugin/pull/831 into.

**Pull request closed without merging**
