### PR TITLE
50844 Fix Email sending and creating data records issue with Honeypot Function on Property Detail Pages

### PR DESCRIPTION
**Pull request by yeneastgate**
related to https://github.com/onOffice-Web-Org/oo-wp-plugin/issues/857
changed log:
Add condition load honeypot on detail page when using ACF

### CODE REVIEW

**Comment by yeneastgate** [comment]
@fredericalpers @andernath I have checked and found that before WordPress version 5.2, the get_the_content function did not work correctly when retrieving the content of a post, which prevented shortcodes from being fetched and scripts from being loaded accordingly.
I have made some changes to use an optimal approach because this is a core attribute in WordPress.
Here is video evidence wordpress version 5.1.19:

https://github.com/user-attachments/assets/13c246b9-b09a-41cf-9c97-6be4d3990f63

**Comment by fredericalpers** [comment]
@yeneastgate Our further tests have shown that:

- The honeypot field is not added to the form at all. Therefore no e-mails are received.
- The problem ONLY seems to exists if the units are to be displayed in the shortcode ([oo_estate units="Units list" view="detail"]). 
- It also does not seem to work if the shortcode with unit list is stored via the Gutenberg "Shortcode".

https://testinstanz-mr.onofficeweb.com/
Here the suggested fix also works for the unit list with the current detail page. As soon as a new detail page is created, the whole functionality with units no longer works. We suspect that the shortcode was stored somewhere outside ACFs/Gutenberg in the past, e.g. in the Classis Editor or in the database.

Please investigate further. Thank you :)

**Comment by yeneastgate** [comment]
@fredericalpers You are right, this issue is related to issue #799,
=> I merged PR #799 into this PR and tested it again using the editors: Classic Editor, Advanced Custom Fields, and Gutenberg editor, and tested the unit detail functionality, and it still works fine.

**Comment by yeneastgate** [comment]
@fredericalpers You are right, this issue is related to issue https://github.com/onOffice-Web-Org/oo-wp-plugin/issues/799,
=> I merged PR https://github.com/onOffice-Web-Org/oo-wp-plugin/issues/799 into this PR and tested it again using the editors: Classic Editor, Advanced Custom Fields, and Gutenberg editor, and tested the unit detail functionality, and it still works fine.

**Comment by fredericalpers** [comment]
@yeneastgate Please double check if you merged the PR's. 

I can not find a commit for it, therefore I'm not able to deploy the build to test everything :)

**Comment by yeneastgate** [comment]
> @yeneastgate Please double check if you merged the PR's.
> 
> I can not find a commit for it, therefore I'm not able to deploy the build to test everything :)

@fredericalpers I have merged it. You can deploy and test it now.

**Comment by fredericalpers** [comment]
This seems to be fixing the problem :) thank you

**Comment by fredericalpers** [comment]
https://github.com/onOffice-Web-Org/oo-wp-plugin/issues/857#issuecomment-2232555992

**Comment by fredericalpers** [comment]
Bereits behoben mit https://github.com/onOffice-Web-Org/oo-wp-plugin/pull/800

**Pull request closed without merging**
