### PR TITLE
43301 Notification of unsaved changes

### PR DESCRIPTION
**Pull request by dai-eastgate**
related to https://github.com/onOffice-Web-Org/oo-wp-plugin/issues/697
changed log:
Update notification of unsaved changes

### CODE REVIEW

**Comment by fredericalpers** [comment]
@dai-eastgate Overall, the changes are looking good, but there are a few issues that need to be addressed before merging.

# Feedback
1. Links that open in a new tab (target=_blank) are not functioning correctly with the new feature. They should be excluded from this functionality.
2. The internal WordPress message should only be triggered when clicking a menu item in the side-menu or admin-menu
3. When repeatedly clicking different menu items, error messages should not stack below each other. Instead, the newest error message should replace the old one.
4. The browser popup should display the text from the WordPress error message. Currently, after clicking "Reload" in the browser popup, the WordPress error message is loaded afterwards.

# Tasks
- [ ] Exlude links with target="blank" from the new feature
- [ ] Ensure the internal WordPress message is only triggered when clicking a menu item
- [ ] Implement logic to prevent stacking of error messages when rerpeatedly clicking different menu items
- [ ] Update the browser popup to display the text from the WordPress error messages

Please address these issues and check the tasklist. Once done, feel free to resubmit the PR for further review. Thank you for your efforts! :)

**Comment by dai-eastgate** [comment]
@fredericalpers I will check it.

**Comment by dai-eastgate** [comment]
> * Update the browser popup to display the text from the WordPress error messages

@fredericalpers According to my investigation, there is currently no solution to update the browser popup to display the text from the WordPress error messages because it is no longer possible to display a custom message in the beforeunload (Please check the documents https://chromestatus.com/feature/5349061406228480)

**Comment by dai-eastgate** [comment]
@fredericalpers @andernath I have fixed it and here is video demo, please review and test this branch again. Thanks!

https://files.fm/u/pfqdykseyx#/view/j9nnaa54ds

**Comment by fredericalpers** [comment]
@dai-eastgate When clicking on the menu items in the admin-bar the notification for unsaved changes does not work.

- [ ] Implement notification also when using the admin-bar menu items

 Please go ahead and make sure it also works when using the admin-bar menu, thank you :)

**Comment by dai-eastgate** [comment]
> @dai-eastgate When clicking on the menu items in the admin-bar the notification for unsaved changes does not work.
> 
> * [ ]  Implement notification also when using the admin-bar menu items
> 
> Please go ahead and make sure it also works when using the admin-bar menu, thank you :)

@fredericalpers I have fixed it and here is video demo, please test this branch again. Thanks!

https://github.com/onOffice-Web-Org/oo-wp-plugin/assets/106214469/c4d23fb9-a02a-47fb-b470-29f9e3d0906b

**Review by andernath — APPROVED** [review]

**Pull request merged**
