### PR TITLE
32986 Default values for estate lists

### PR DESCRIPTION
**Pull request by dai-eastgate**
related to https://github.com/onOffice-Web-Org/oo-wp-plugin/issues/491

changed log : 
Add default value to estate

### CODE REVIEW

**Review by andernath — COMMENTED** [review]
I finished review with some question. Could you please fix or answer. Thanks.

**Review by andernath — COMMENTED** [review]
Thank you! I finished review.
Please do NOT merge this branch to master right now. 
I'm still testing this feature, :)

**Review by andernath — APPROVED** [review]
Please do not merge to master right now.

**Comment by dai-eastgate** [comment]
@andernath Yes, I won't merge it into master. While you test, I will also test with you.

**Comment by fredericalpers** [comment]
Closing this PR for now since theres more investigation on the issue to be done.

**Comment by fredericalpers** [comment]
This feature unfortunately has to be postponed indefinetely. See: https://github.com/onOffice-Web-Org/oo-wp-plugin/issues/491#issuecomment-1814236568

**Comment by fredericalpers** [comment]
Closed until further notice.

https://github.com/onOffice-Web-Org/oo-wp-plugin/issues/491#issuecomment-1814236568

**Pull request closed without merging**
