### PR TITLE
32991 Order properties by tags

### PR DESCRIPTION
**Pull request by yeneastgate**
related to https://github.com/onOffice-Web-Org/oo-wp-plugin/issues/550
changed log:
Add order properties by tags feature

### CODE REVIEW

**Comment by fredericalpers** [comment]
Hi @yeneastgate ,

While testing the pull request, I encountered a fatal error in the backend of the plugin when trying to edit the property list. Please check the debug.log from today which I posted down below.

<details><summary>debug.log 2024-07-31</summary>
<p>

[31-Jul-2024 01:38:21 UTC] PHP Deprecated:  Constant FILTER_SANITIZE_STRING is deprecated in /www/htdocs/w01dbd85/testinstanz-fal.onofficeweb.com/htdocs/wp-content/plugins/onoffice-for-wp-websites/plugin/FormPostHandler.php on line 82
[31-Jul-2024 01:38:21 UTC] PHP Deprecated:  Constant FILTER_SANITIZE_STRING is deprecated in /www/htdocs/w01dbd85/testinstanz-fal.onofficeweb.com/htdocs/wp-content/plugins/onoffice-for-wp-websites/plugin/FormPostHandler.php on line 82
[31-Jul-2024 01:38:22 UTC] Automatic updates starting...
[31-Jul-2024 01:38:23 UTC] PHP Deprecated:  Constant FILTER_SANITIZE_STRING is deprecated in /www/htdocs/w01dbd85/testinstanz-fal.onofficeweb.com/htdocs/wp-content/plugins/onoffice-for-wp-websites/plugin/FormPostHandler.php on line 82
[31-Jul-2024 01:38:23 UTC] Automatic updates complete.
[31-Jul-2024 01:38:23 UTC] PHP Deprecated:  Constant FILTER_SANITIZE_STRING is deprecated in /www/htdocs/w01dbd85/testinstanz-fal.onofficeweb.com/htdocs/wp-content/plugins/onoffice-for-wp-websites/plugin/FormPostHandler.php on line 82
[31-Jul-2024 07:27:50 UTC] PHP Deprecated:  Constant FILTER_SANITIZE_STRING is deprecated in /www/htdocs/w01dbd85/testinstanz-fal.onofficeweb.com/htdocs/wp-content/plugins/onoffice-for-wp-websites/plugin/FormPostHandler.php on line 82
[31-Jul-2024 07:27:53 UTC] PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in /www/htdocs/w01dbd85/testinstanz-fal.onofficeweb.com/htdocs/wp-includes/functions.php on line 7300
[31-Jul-2024 07:27:53 UTC] PHP Deprecated:  str_replace(): Passing null to parameter #3 ($subject) of type array|string is deprecated in /www/htdocs/w01dbd85/testinstanz-fal.onofficeweb.com/htdocs/wp-includes/functions.php on line 2189
[31-Jul-2024 07:27:53 UTC] PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in /www/htdocs/w01dbd85/testinstanz-fal.onofficeweb.com/htdocs/wp-includes/functions.php on line 7300
[31-Jul-2024 07:27:53 UTC] PHP Deprecated:  str_replace(): Passing null to parameter #3 ($subject) of type array|string is deprecated in /www/htdocs/w01dbd85/testinstanz-fal.onofficeweb.com/htdocs/wp-includes/functions.php on line 2189
[31-Jul-2024 07:27:53 UTC] PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in /www/htdocs/w01dbd85/testinstanz-fal.onofficeweb.com/htdocs/wp-includes/functions.php on line 7300
[31-Jul-2024 07:27:53 UTC] PHP Deprecated:  str_replace(): Passing null to parameter #3 ($subject) of type array|string is deprecated in /www/htdocs/w01dbd85/testinstanz-fal.onofficeweb.com/htdocs/wp-includes/functions.php on line 2189
[31-Jul-2024 07:27:53 UTC] PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in /www/htdocs/w01dbd85/testinstanz-fal.onofficeweb.com/htdocs/wp-includes/functions.php on line 7300
[31-Jul-2024 07:27:53 UTC] PHP Deprecated:  str_replace(): Passing null to parameter #3 ($subject) of type array|string is deprecated in /www/htdocs/w01dbd85/testinstanz-fal.onofficeweb.com/htdocs/wp-includes/functions.php on line 2189
[31-Jul-2024 07:27:54 UTC] PHP Deprecated:  Constant FILTER_SANITIZE_STRING is deprecated in /www/htdocs/w01dbd85/testinstanz-fal.onofficeweb.com/htdocs/wp-content/plugins/onoffice-for-wp-websites/plugin/FormPostHandler.php on line 82
[31-Jul-2024 07:27:54 UTC] PHP Deprecated:  Constant FILTER_SANITIZE_STRING is deprecated in /www/htdocs/w01dbd85/testinstanz-fal.onofficeweb.com/htdocs/wp-content/plugins/onoffice-for-wp-websites/plugin/FormPostHandler.php on line 82
[31-Jul-2024 07:28:55 UTC] PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in /www/htdocs/w01dbd85/testinstanz-fal.onofficeweb.com/htdocs/wp-includes/functions.php on line 7300
[31-Jul-2024 07:28:55 UTC] PHP Deprecated:  str_replace(): Passing null to parameter #3 ($subject) of type array|string is deprecated in /www/htdocs/w01dbd85/testinstanz-fal.onofficeweb.com/htdocs/wp-includes/functions.php on line 2189
[31-Jul-2024 07:28:55 UTC] PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in /www/htdocs/w01dbd85/testinstanz-fal.onofficeweb.com/htdocs/wp-includes/functions.php on line 7300
[31-Jul-2024 07:28:55 UTC] PHP Deprecated:  str_replace(): Passing null to parameter #3 ($subject) of type array|string is deprecated in /www/htdocs/w01dbd85/testinstanz-fal.onofficeweb.com/htdocs/wp-includes/functions.php on line 2189
[31-Jul-2024 07:28:55 UTC] PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in /www/htdocs/w01dbd85/testinstanz-fal.onofficeweb.com/htdocs/wp-includes/functions.php on line 7300
[31-Jul-2024 07:28:55 UTC] PHP Deprecated:  str_replace(): Passing null to parameter #3 ($subject) of type array|string is deprecated in /www/htdocs/w01dbd85/testinstanz-fal.onofficeweb.com/htdocs/wp-includes/functions.php on line 2189
[31-Jul-2024 07:28:55 UTC] PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in /www/htdocs/w01dbd85/testinstanz-fal.onofficeweb.com/htdocs/wp-includes/functions.php on line 7300
[31-Jul-2024 07:28:55 UTC] PHP Deprecated:  str_replace(): Passing null to parameter #3 ($subject) of type array|string is deprecated in /www/htdocs/w01dbd85/testinstanz-fal.onofficeweb.com/htdocs/wp-includes/functions.php on line 2189
[31-Jul-2024 07:28:56 UTC] PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in /www/htdocs/w01dbd85/testinstanz-fal.onofficeweb.com/htdocs/wp-includes/functions.php on line 7300
[31-Jul-2024 07:28:56 UTC] PHP Deprecated:  str_replace(): Passing null to parameter #3 ($subject) of type array|string is deprecated in /www/htdocs/w01dbd85/testinstanz-fal.onofficeweb.com/htdocs/wp-includes/functions.php on line 2189
[31-Jul-2024 07:28:56 UTC] PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in /www/htdocs/w01dbd85/testinstanz-fal.onofficeweb.com/htdocs/wp-includes/functions.php on line 7300
[31-Jul-2024 07:28:56 UTC] PHP Deprecated:  str_replace(): Passing null to parameter #3 ($subject) of type array|string is deprecated in /www/htdocs/w01dbd85/testinstanz-fal.onofficeweb.com/htdocs/wp-includes/functions.php on line 2189
[31-Jul-2024 07:28:56 UTC] PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in /www/htdocs/w01dbd85/testinstanz-fal.onofficeweb.com/htdocs/wp-includes/functions.php on line 7300
[31-Jul-2024 07:28:56 UTC] PHP Deprecated:  str_replace(): Passing null to parameter #3 ($subject) of type array|string is deprecated in /www/htdocs/w01dbd85/testinstanz-fal.onofficeweb.com/htdocs/wp-includes/functions.php on line 2189
[31-Jul-2024 07:28:56 UTC] PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in /www/htdocs/w01dbd85/testinstanz-fal.onofficeweb.com/htdocs/wp-includes/functions.php on line 7300
[31-Jul-2024 07:28:56 UTC] PHP Deprecated:  str_replace(): Passing null to parameter #3 ($subject) of type array|string is deprecated in /www/htdocs/w01dbd85/testinstanz-fal.onofficeweb.com/htdocs/wp-includes/functions.php on line 2189
[31-Jul-2024 07:28:57 UTC] PHP Deprecated:  Constant FILTER_SANITIZE_STRING is deprecated in /www/htdocs/w01dbd85/testinstanz-fal.onofficeweb.com/htdocs/wp-content/plugins/onoffice-for-wp-websites/plugin/FormPostHandler.php on line 82
[31-Jul-2024 07:28:59 UTC] PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in /www/htdocs/w01dbd85/testinstanz-fal.onofficeweb.com/htdocs/wp-includes/functions.php on line 7300
[31-Jul-2024 07:28:59 UTC] PHP Deprecated:  str_replace(): Passing null to parameter #3 ($subject) of type array|string is deprecated in /www/htdocs/w01dbd85/testinstanz-fal.onofficeweb.com/htdocs/wp-includes/functions.php on line 2189
[31-Jul-2024 07:28:59 UTC] PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in /www/htdocs/w01dbd85/testinstanz-fal.onofficeweb.com/htdocs/wp-includes/functions.php on line 7300
[31-Jul-2024 07:28:59 UTC] PHP Deprecated:  str_replace(): Passing null to parameter #3 ($subject) of type array|string is deprecated in /www/htdocs/w01dbd85/testinstanz-fal.onofficeweb.com/htdocs/wp-includes/functions.php on line 2189
[31-Jul-2024 07:28:59 UTC] PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in /www/htdocs/w01dbd85/testinstanz-fal.onofficeweb.com/htdocs/wp-includes/functions.php on line 7300
[31-Jul-2024 07:28:59 UTC] PHP Deprecated:  str_replace(): Passing null to parameter #3 ($subject) of type array|string is deprecated in /www/htdocs/w01dbd85/testinstanz-fal.onofficeweb.com/htdocs/wp-includes/functions.php on line 2189
[31-Jul-2024 07:28:59 UTC] PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in /www/htdocs/w01dbd85/testinstanz-fal.onofficeweb.com/htdocs/wp-includes/functions.php on line 7300
[31-Jul-2024 07:28:59 UTC] PHP Deprecated:  str_replace(): Passing null to parameter #3 ($subject) of type array|string is deprecated in /www/htdocs/w01dbd85/testinstanz-fal.onofficeweb.com/htdocs/wp-includes/functions.php on line 2189
[31-Jul-2024 07:29:50 UTC] PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in /www/htdocs/w01dbd85/testinstanz-fal.onofficeweb.com/htdocs/wp-includes/functions.php on line 7300
[31-Jul-2024 07:29:50 UTC] PHP Deprecated:  str_replace(): Passing null to parameter #3 ($subject) of type array|string is deprecated in /www/htdocs/w01dbd85/testinstanz-fal.onofficeweb.com/htdocs/wp-includes/functions.php on line 2189
[31-Jul-2024 07:29:50 UTC] PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in /www/htdocs/w01dbd85/testinstanz-fal.onofficeweb.com/htdocs/wp-includes/functions.php on line 7300
[31-Jul-2024 07:29:50 UTC] PHP Deprecated:  str_replace(): Passing null to parameter #3 ($subject) of type array|string is deprecated in /www/htdocs/w01dbd85/testinstanz-fal.onofficeweb.com/htdocs/wp-includes/functions.php on line 2189
[31-Jul-2024 07:29:50 UTC] PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in /www/htdocs/w01dbd85/testinstanz-fal.onofficeweb.com/htdocs/wp-includes/functions.php on line 7300
[31-Jul-2024 07:29:50 UTC] PHP Deprecated:  str_replace(): Passing null to parameter #3 ($subject) of type array|string is deprecated in /www/htdocs/w01dbd85/testinstanz-fal.onofficeweb.com/htdocs/wp-includes/functions.php on line 2189
[31-Jul-2024 07:29:50 UTC] PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in /www/htdocs/w01dbd85/testinstanz-fal.onofficeweb.com/htdocs/wp-includes/functions.php on line 7300
[31-Jul-2024 07:29:50 UTC] PHP Deprecated:  str_replace(): Passing null to parameter #3 ($subject) of type array|string is deprecated in /www/htdocs/w01dbd85/testinstanz-fal.onofficeweb.com/htdocs/wp-includes/functions.php on line 2189
[31-Jul-2024 07:29:50 UTC] PHP Deprecated:  Constant FILTER_SANITIZE_STRING is deprecated in /www/htdocs/w01dbd85/testinstanz-fal.onofficeweb.com/htdocs/wp-content/plugins/onoffice-for-wp-websites/plugin/FormPostHandler.php on line 82
[31-Jul-2024 07:29:50 UTC] PHP Deprecated:  Constant FILTER_SANITIZE_STRING is deprecated in /www/htdocs/w01dbd85/testinstanz-fal.onofficeweb.com/htdocs/wp-content/plugins/onoffice-for-wp-websites/plugin/FormPostHandler.php on line 82
[31-Jul-2024 07:29:56 UTC] PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in /www/htdocs/w01dbd85/testinstanz-fal.onofficeweb.com/htdocs/wp-includes/functions.php on line 7300
[31-Jul-2024 07:29:56 UTC] PHP Deprecated:  str_replace(): Passing null to parameter #3 ($subject) of type array|string is deprecated in /www/htdocs/w01dbd85/testinstanz-fal.onofficeweb.com/htdocs/wp-includes/functions.php on line 2189
[31-Jul-2024 07:29:56 UTC] PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in /www/htdocs/w01dbd85/testinstanz-fal.onofficeweb.com/htdocs/wp-includes/functions.php on line 7300
[31-Jul-2024 07:29:56 UTC] PHP Deprecated:  str_replace(): Passing null to parameter #3 ($subject) of type array|string is deprecated in /www/htdocs/w01dbd85/testinstanz-fal.onofficeweb.com/htdocs/wp-includes/functions.php on line 2189
[31-Jul-2024 07:29:56 UTC] PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in /www/htdocs/w01dbd85/testinstanz-fal.onofficeweb.com/htdocs/wp-includes/functions.php on line 7300
[31-Jul-2024 07:29:56 UTC] PHP Deprecated:  str_replace(): Passing null to parameter #3 ($subject) of type array|string is deprecated in /www/htdocs/w01dbd85/testinstanz-fal.onofficeweb.com/htdocs/wp-includes/functions.php on line 2189
[31-Jul-2024 07:29:56 UTC] PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in /www/htdocs/w01dbd85/testinstanz-fal.onofficeweb.com/htdocs/wp-includes/functions.php on line 7300
[31-Jul-2024 07:29:56 UTC] PHP Deprecated:  str_replace(): Passing null to parameter #3 ($subject) of type array|string is deprecated in /www/htdocs/w01dbd85/testinstanz-fal.onofficeweb.com/htdocs/wp-includes/functions.php on line 2189
[31-Jul-2024 07:29:57 UTC] PHP Deprecated:  Constant FILTER_SANITIZE_STRING is deprecated in /www/htdocs/w01dbd85/testinstanz-fal.onofficeweb.com/htdocs/wp-content/plugins/onoffice-for-wp-websites/plugin/FormPostHandler.php on line 82
[31-Jul-2024 07:29:58 UTC] PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in /www/htdocs/w01dbd85/testinstanz-fal.onofficeweb.com/htdocs/wp-includes/functions.php on line 7300
[31-Jul-2024 07:29:58 UTC] PHP Deprecated:  str_replace(): Passing null to parameter #3 ($subject) of type array|string is deprecated in /www/htdocs/w01dbd85/testinstanz-fal.onofficeweb.com/htdocs/wp-includes/functions.php on line 2189
[31-Jul-2024 07:29:58 UTC] PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in /www/htdocs/w01dbd85/testinstanz-fal.onofficeweb.com/htdocs/wp-includes/functions.php on line 7300
[31-Jul-2024 07:29:58 UTC] PHP Deprecated:  str_replace(): Passing null to parameter #3 ($subject) of type array|string is deprecated in /www/htdocs/w01dbd85/testinstanz-fal.onofficeweb.com/htdocs/wp-includes/functions.php on line 2189
[31-Jul-2024 07:29:58 UTC] PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in /www/htdocs/w01dbd85/testinstanz-fal.onofficeweb.com/htdocs/wp-includes/functions.php on line 7300
[31-Jul-2024 07:29:58 UTC] PHP Deprecated:  str_replace(): Passing null to parameter #3 ($subject) of type array|string is deprecated in /www/htdocs/w01dbd85/testinstanz-fal.onofficeweb.com/htdocs/wp-includes/functions.php on line 2189
[31-Jul-2024 07:29:58 UTC] PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in /www/htdocs/w01dbd85/testinstanz-fal.onofficeweb.com/htdocs/wp-includes/functions.php on line 7300
[31-Jul-2024 07:29:58 UTC] PHP Deprecated:  str_replace(): Passing null to parameter #3 ($subject) of type array|string is deprecated in /www/htdocs/w01dbd85/testinstanz-fal.onofficeweb.com/htdocs/wp-includes/functions.php on line 2189
[31-Jul-2024 07:29:59 UTC] PHP Deprecated:  strip_tags(): Passing null to parameter #1 ($string) of type string is deprecated in /www/htdocs/w01dbd85/testinstanz-fal.onofficeweb.com/htdocs/wp-admin/admin-header.php on line 36
[31-Jul-2024 07:29:59 UTC] PHP Warning:  Undefined array key "markedPropertiesSort" in /www/htdocs/w01dbd85/testinstanz-fal.onofficeweb.com/htdocs/wp-content/plugins/onoffice-for-wp-websites/plugin/DataView/DataListViewFactory.php on line 87
[31-Jul-2024 07:29:59 UTC] PHP Fatal error:  Uncaught TypeError: onOffice\WPlugin\DataView\DataListView::setMarkedPropertiesSort(): Argument #1 ($markedPropertiesSort) must be of type string, null given, called in /www/htdocs/w01dbd85/testinstanz-fal.onofficeweb.com/htdocs/wp-content/plugins/onoffice-for-wp-websites/plugin/DataView/DataListViewFactory.php on line 87 and defined in /www/htdocs/w01dbd85/testinstanz-fal.onofficeweb.com/htdocs/wp-content/plugins/onoffice-for-wp-websites/plugin/DataView/DataListView.php:448
Stack trace:
#0 /www/htdocs/w01dbd85/testinstanz-fal.onofficeweb.com/htdocs/wp-content/plugins/onoffice-for-wp-websites/plugin/DataView/DataListViewFactory.php(87): onOffice\WPlugin\DataView\DataListView->setMarkedPropertiesSort(NULL)
#1 /www/htdocs/w01dbd85/testinstanz-fal.onofficeweb.com/htdocs/wp-content/plugins/onoffice-for-wp-websites/plugin/Gui/AdminPageEstateListSettings.php(295): onOffice\WPlugin\DataView\DataListViewFactory->createListViewByRow(Array)
#2 /www/htdocs/w01dbd85/testinstanz-fal.onofficeweb.com/htdocs/wp-content/plugins/onoffice-for-wp-websites/plugin/Gui/AdminPageEstateListSettingsBase.php(69): onOffice\WPlugin\Gui\AdminPageEstateListSettings->validate('1')
#3 /www/htdocs/w01dbd85/testinstanz-fal.onofficeweb.com/htdocs/wp-content/plugins/onoffice-for-wp-websites/plugin/Gui/AdminPageBase.php(76): onOffice\WPlugin\Gui\AdminPageEstateListSettingsBase->renderContent()
#4 /www/htdocs/w01dbd85/testinstanz-fal.onofficeweb.com/htdocs/wp-includes/class-wp-hook.php(324): onOffice\WPlugin\Gui\AdminPageBase->render('')
#5 /www/htdocs/w01dbd85/testinstanz-fal.onofficeweb.com/htdocs/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters('', Array)
#6 /www/htdocs/w01dbd85/testinstanz-fal.onofficeweb.com/htdocs/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#7 /www/htdocs/w01dbd85/testinstanz-fal.onofficeweb.com/htdocs/wp-admin/admin.php(259): do_action('admin_page_onof...')
#8 {main}
  thrown in /www/htdocs/w01dbd85/testinstanz-fal.onofficeweb.com/htdocs/wp-content/plugins/onoffice-for-wp-websites/plugin/DataView/DataListView.php on line 448
[31-Jul-2024 07:30:00 UTC] PHP Deprecated:  Constant FILTER_SANITIZE_STRING is deprecated in /www/htdocs/w01dbd85/testinstanz-fal.onofficeweb.com/htdocs/wp-content/plugins/onoffice-for-wp-websites/plugin/FormPostHandler.php on line 82
[31-Jul-2024 07:30:00 UTC] PHP Deprecated:  Constant FILTER_SANITIZE_STRING is deprecated in /www/htdocs/w01dbd85/testinstanz-fal.onofficeweb.com/htdocs/wp-content/plugins/onoffice-for-wp-websites/plugin/FormPostHandler.php on line 82
[31-Jul-2024 07:30:00 UTC] PHP Deprecated:  Constant FILTER_SANITIZE_STRING is deprecated in /www/htdocs/w01dbd85/testinstanz-fal.onofficeweb.com/htdocs/wp-content/plugins/onoffice-for-wp-websites/plugin/FormPostHandler.php on line 82
[31-Jul-2024 07:30:06 UTC] PHP Deprecated:  Constant FILTER_SANITIZE_STRING is deprecated in /www/htdocs/w01dbd85/testinstanz-fal.onofficeweb.com/htdocs/wp-content/plugins/onoffice-for-wp-websites/plugin/FormPostHandler.php on line 82
[31-Jul-2024 07:30:06 UTC] PHP Warning:  Undefined array key "markedPropertiesSort" in /www/htdocs/w01dbd85/testinstanz-fal.onofficeweb.com/htdocs/wp-content/plugins/onoffice-for-wp-websites/plugin/DataView/DataListViewFactory.php on line 87
[31-Jul-2024 07:30:06 UTC] PHP Fatal error:  Uncaught TypeError: onOffice\WPlugin\DataView\DataListView::setMarkedPropertiesSort(): Argument #1 ($markedPropertiesSort) must be of type string, null given, called in /www/htdocs/w01dbd85/testinstanz-fal.onofficeweb.com/htdocs/wp-content/plugins/onoffice-for-wp-websites/plugin/DataView/DataListViewFactory.php on line 87 and defined in /www/htdocs/w01dbd85/testinstanz-fal.onofficeweb.com/htdocs/wp-content/plugins/onoffice-for-wp-websites/plugin/DataView/DataListView.php:448
Stack trace:
#0 /www/htdocs/w01dbd85/testinstanz-fal.onofficeweb.com/htdocs/wp-content/plugins/onoffice-for-wp-websites/plugin/DataView/DataListViewFactory.php(87): onOffice\WPlugin\DataView\DataListView->setMarkedPropertiesSort(NULL)
#1 /www/htdocs/w01dbd85/testinstanz-fal.onofficeweb.com/htdocs/wp-content/plugins/onoffice-for-wp-websites/plugin/DataView/DataListViewFactoryBase.php(57): onOffice\WPlugin\DataView\DataListViewFactory->createListViewByRow(Array)
#2 /www/htdocs/w01dbd85/testinstanz-fal.onofficeweb.com/htdocs/wp-content/plugins/onoffice-for-wp-websites/plugin/Controller/ContentFilter/ContentFilterShortCodeEstateList.php(114): onOffice\WPlugin\DataView\DataListViewFactoryBase->getListViewByName('Immobilienliste...')
#3 /www/htdocs/w01dbd85/testinstanz-fal.onofficeweb.com/htdocs/wp-content/plugins/onoffice-for-wp-websites/plugin/Controller/ContentFilter/ContentFilterShortCodeEstate.php(94): onOffice\WPlugin\Controller\ContentFilter\ContentFilterShortCodeEstateList->render(Array)
#4 /www/htdocs/w01dbd85/testinstanz-fal.onofficeweb.com/htdocs/wp-content/plugins/onoffice-for-wp-websites/plugin/Controller/ContentFilter/ContentFilterShortCodeEstate.php(69): onOffice\WPlugin\Controller\ContentFilter\ContentFilterShortCodeEstate->buildReplacementString(Array)
#5 /www/htdocs/w01dbd85/testinstanz-fal.onofficeweb.com/htdocs/wp-content/plugins/onoffice-for-wp-websites/plugin/Controller/ContentFilter/ContentFilterShortCodeRegistrator.php(59): onOffice\WPlugin\Controller\ContentFilter\ContentFilterShortCodeEstate->replaceShortCodes(Array)
#6 /www/htdocs/w01dbd85/testinstanz-fal.onofficeweb.com/htdocs/wp-includes/shortcodes.php(434): onOffice\WPlugin\Controller\ContentFilter\ContentFilterShortCodeRegistrator->onOffice\WPlugin\Controller\ContentFilter\{closure}(Array, '', 'oo_estate')
#7 [internal function]: do_shortcode_tag(Array)
#8 /www/htdocs/w01dbd85/testinstanz-fal.onofficeweb.com/htdocs/wp-includes/shortcodes.php(273): preg_replace_callback('/\\[(\\[?)(oo_est...', 'do_shortcode_ta...', '[oo_estate view...')
#9 /www/htdocs/w01dbd85/testinstanz-fal.onofficeweb.com/htdocs/wp-includes/class-wp-hook.php(324): do_shortcode('[oo_estate view...')
#10 /www/htdocs/w01dbd85/testinstanz-fal.onofficeweb.com/htdocs/wp-includes/plugin.php(205): WP_Hook->apply_filters('[oo_estate view...', Array)
#11 /www/htdocs/w01dbd85/testinstanz-fal.onofficeweb.com/htdocs/wp-includes/post-template.php(256): apply_filters('the_content', '<!-- wp:shortco...')
#12 /www/htdocs/w01dbd85/testinstanz-fal.onofficeweb.com/htdocs/wp-content/themes/oceanwp/partials/page/article.php(20): the_content()
#13 /www/htdocs/w01dbd85/testinstanz-fal.onofficeweb.com/htdocs/wp-includes/template.php(812): require('/www/htdocs/w01...')
#14 /www/htdocs/w01dbd85/testinstanz-fal.onofficeweb.com/htdocs/wp-includes/template.php(745): load_template('/www/htdocs/w01...', false, Array)
#15 /www/htdocs/w01dbd85/testinstanz-fal.onofficeweb.com/htdocs/wp-includes/general-template.php(206): locate_template(Array, true, false, Array)
#16 /www/htdocs/w01dbd85/testinstanz-fal.onofficeweb.com/htdocs/wp-content/themes/oceanwp/partials/page/layout.php(20): get_template_part('partials/page/a...')
#17 /www/htdocs/w01dbd85/testinstanz-fal.onofficeweb.com/htdocs/wp-includes/template.php(812): require('/www/htdocs/w01...')
#18 /www/htdocs/w01dbd85/testinstanz-fal.onofficeweb.com/htdocs/wp-includes/template.php(745): load_template('/www/htdocs/w01...', false, Array)
#19 /www/htdocs/w01dbd85/testinstanz-fal.onofficeweb.com/htdocs/wp-includes/general-template.php(206): locate_template(Array, true, false, Array)
#20 /www/htdocs/w01dbd85/testinstanz-fal.onofficeweb.com/htdocs/wp-content/themes/oceanwp/page.php(36): get_template_part('partials/page/l...')
#21 /www/htdocs/w01dbd85/testinstanz-fal.onofficeweb.com/htdocs/wp-includes/template-loader.php(106): include('/www/htdocs/w01...')
#22 /www/htdocs/w01dbd85/testinstanz-fal.onofficeweb.com/htdocs/wp-blog-header.php(19): require_once('/www/htdocs/w01...')
#23 /www/htdocs/w01dbd85/testinstanz-fal.onofficeweb.com/htdocs/index.php(17): require('/www/htdocs/w01...')
#24 {main}
  thrown in /www/htdocs/w01dbd85/testinstanz-fal.onofficeweb.com/htdocs/wp-content/plugins/onoffice-for-wp-websites/plugin/DataView/DataListView.php on line 448
[31-Jul-2024 07:30:06 UTC] PHP Deprecated:  Constant FILTER_SANITIZE_STRING is deprecated in /www/htdocs/w01dbd85/testinstanz-fal.onofficeweb.com/htdocs/wp-content/plugins/onoffice-for-wp-websites/plugin/FormPostHandler.php on line 82
[31-Jul-2024 07:30:16 UTC] PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in /www/htdocs/w01dbd85/testinstanz-fal.onofficeweb.com/htdocs/wp-includes/functions.php on line 7300
[31-Jul-2024 07:30:16 UTC] PHP Deprecated:  str_replace(): Passing null to parameter #3 ($subject) of type array|string is deprecated in /www/htdocs/w01dbd85/testinstanz-fal.onofficeweb.com/htdocs/wp-includes/functions.php on line 2189
[31-Jul-2024 07:30:16 UTC] PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in /www/htdocs/w01dbd85/testinstanz-fal.onofficeweb.com/htdocs/wp-includes/functions.php on line 7300
[31-Jul-2024 07:30:16 UTC] PHP Deprecated:  str_replace(): Passing null to parameter #3 ($subject) of type array|string is deprecated in /www/htdocs/w01dbd85/testinstanz-fal.onofficeweb.com/htdocs/wp-includes/functions.php on line 2189
[31-Jul-2024 07:30:16 UTC] PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in /www/htdocs/w01dbd85/testinstanz-fal.onofficeweb.com/htdocs/wp-includes/functions.php on line 7300
[31-Jul-2024 07:30:16 UTC] PHP Deprecated:  str_replace(): Passing null to parameter #3 ($subject) of type array|string is deprecated in /www/htdocs/w01dbd85/testinstanz-fal.onofficeweb.com/htdocs/wp-includes/functions.php on line 2189
[31-Jul-2024 07:30:16 UTC] PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in /www/htdocs/w01dbd85/testinstanz-fal.onofficeweb.com/htdocs/wp-includes/functions.php on line 7300
[31-Jul-2024 07:30:16 UTC] PHP Deprecated:  str_replace(): Passing null to parameter #3 ($subject) of type array|string is deprecated in /www/htdocs/w01dbd85/testinstanz-fal.onofficeweb.com/htdocs/wp-includes/functions.php on line 2189
[31-Jul-2024 07:30:16 UTC] PHP Deprecated:  Constant FILTER_SANITIZE_STRING is deprecated in /www/htdocs/w01dbd85/testinstanz-fal.onofficeweb.com/htdocs/wp-content/plugins/onoffice-for-wp-websites/plugin/FormPostHandler.php on line 82


</p>
</details>

**Comment by yeneastgate** [comment]
@fredericalpers i will check it.

**Comment by yeneastgate** [comment]
> [31-Jul-2024 07:30:06 UTC] PHP Warning: Undefined array key "markedPropertiesSort" in /www/htdocs/w01dbd85/testinstanz-fal.onofficeweb.com/htdocs/wp-content/plugins/onoffice-for-wp-websites/plugin/DataView/DataListViewFactory.php on line 87
> [31-Jul-2024 07:30:06 UTC] PHP Fatal error: Uncaught TypeError: onOffice\WPlugin\DataView\DataListView::setMarkedPropertiesSort(): Argument #1 ($markedPropertiesSort) must be of type string, null given, called in /www/htdocs/w01dbd85/testinstanz-fal.onofficeweb.com/htdocs/wp-content/plugins/onoffice-for-wp-websites/plugin/DataView/DataListViewFactory.php on line 87 and defined in /www/htdocs/w01dbd85/testinstanz-fal.onofficeweb.com/htdocs/wp-content/plugins/onoffice-for-wp-websites/plugin/DataView/DataListView.php:448
> Stack trace:
> #0 /www/htdocs/w01dbd85/testinstanz-fal.onofficeweb.com/htdocs/wp-content/plugins/onoffice-for-wp-websites/plugin/DataView/DataListViewFactory.php(87): onOffice\WPlugin\DataView\DataListView->setMarkedPropertiesSort(NULL)
> #1 /www/htdocs/w01dbd85/testinstanz-fal.onofficeweb.com/htdocs/wp-content/plugins/onoffice-for-wp-websites/plugin/DataView/DataListViewFactoryBase.php(57): onOffice\WPlugin\DataView\DataListViewFactory->createListViewByRow(Array)

@fredericalpers Could you please try downgrading the plugin version to 43 to check again? The issue seems to occur only when the oo_plugin_listviews table has not been updated.
image

**Comment by miauzjpg** [comment]
grafik
select2 arrow is not correct, please use the chevron icon like in "Sort direction". The height of the box is also too high.

**Review by miauzjpg — APPROVED** [review]
everything fine

**Pull request merged**
