### PR TITLE
40394 Detail Page > Needed Filter Hook or Option to stopping redirection

### PR DESCRIPTION
**Pull request by yeneastgate**
related to https://github.com/onOffice-Web-Org/oo-wp-plugin/issues/558
change log:
Update filter hook to stopping redirection

### CODE REVIEW

**Comment by BenjaminZekavica** [comment]
@yeneastgate It looks good :) Thank you. But one thing: 
In the function: **getUrlWithEstateTitle** for the path of the variable: $**urlLsSwitcher** is a mistake, if somebody has WP installation in subfolder. 

If I request the url on the detail page the url is than dubble and I see the 404 Page Template. This vari. has to fix it **$newPath**

Requested URL: http://localhost/rezac/detail/243/
Redirect to:  http://localhost**/rezac/rezac/**detail/243/

You see its dubble names inside the URL. Do you can fix this?

**Comment by yeneastgate** [comment]
> @yeneastgate It looks good :) Thank you. But one thing: In the function: **getUrlWithEstateTitle** for the path of the variable: $**urlLsSwitcher** is a mistake, if somebody has WP installation in subfolder.
> 
> If I request the url on the detail page the url is than dubble and I see the 404 Page Template. This vari. has to fix it **$newPath**
> 
> Requested URL: http://localhost/rezac/detail/243/ Redirect to: http://localhost**/rezac/rezac/**detail/243/
> 
> You see its dubble names inside the URL. Do you can fix this?

@BenjaminZekavica I will check it. Thanks!

**Comment by yeneastgate** [comment]
@BenjaminZekavica I fixed it. Please watch my video demo and let me know your opinions. Thanks!

https://github.com/onOffice-Web-Org/oo-wp-plugin/assets/104892108/cb6c083e-9edb-4cba-9cd1-a928fb8b280d

**Review by andernath — APPROVED** [review]
ready to test

**Pull request merged**
