### PR TITLE
40398 missing field types

### PR DESCRIPTION
**Pull request by dai-eastgate**
related to https://github.com/onOffice-Web-Org/oo-wp-plugin/issues/634

changed log :
Update missing field types

### CODE REVIEW

**Comment by andernath** [comment]
Happy new year @yeneastgate and @dai-eastgate 

Could someone please resolve these conflicts? :)

**Comment by dai-eastgate** [comment]
> Happy new year @yeneastgate and @dai-eastgate
> 
> Could someone please resolve these conflicts? :)

Happy new year! I will resolve it now :)

**Review by andernath — DISMISSED** [review]

**Comment by andernath** [comment]
@dai-eastgate @yeneastgate 

While testing on version 4.16-13-g00be49f3 a fatal error occurs every time I create a new applicant form or a new applicant search.	

2024-01-05 05_16_57-Window
	
```
Fatal error: Uncaught The API returned an error with code 170 and the following message: No read permission for this user The request that caused this error was: 
{ "actionid": "urn:onoffice-de-ns:smart:2.5:smartml:action:read", "resourceid": "", "resourcetype": "user", "parameters": { "data": [ "Vorname", "Nachname", "Name", "Kuerzel" ], "filter": { "Nr": [ { "op": "in", "val": [ 21, 25 ] } ] } } } onOffice\WPlugin\API\ApiClientException in /www/htdocs/w01bee5f/w3pm.onofficeweb.com/htdocs/wp-content/plugins/onoffice-for-wp-websites/plugin/API/APIClientExceptionFactory.php:53 
Stack trace: #0 /www/htdocs/w01bee5f/w3pm.onofficeweb.com/htdocs/wp-content/plugins/onoffice-for-wp-websites/plugin/API/APIClientActionGeneric.php(85): onOffice\WPlugin\API\APIClientExcepti in /www/htdocs/w01bee5f/w3pm.onofficeweb.com/htdocs/wp-content/plugins/onoffice-for-wp-websites/plugin/API/APIClientExceptionFactory.php on line 53
```

Could you please check this?

**Comment by yeneastgate** [comment]
@andernath I will check and let you know as soon as possible. Thanks!

**Comment by yeneastgate** [comment]
@andernath @fredericalpers 
- I found the cause of this bug:
In the code, I used this API "https://apidoc.onoffice.de/actions/datensatz-lesen/user/".
with the binding conditions:
You need read permission to query user data via API. This can be set under “Extras->Einstellungen->Benutzer” / “Extras->Settings->User”. Choose the tab “API user”, then the tab “Rights” with the setting “Benutzerdaten über API auslesen” / “Read out user data by API”.

- My purpose for using this API:
I need to get information "short name of the user(Kuerzel)" to display the "list Users" for the "supervisor" field.
=> In my opinion, this above bug is because you have not set the "Read out user data by API" permission on onOffice Enterprise.

- However, we have **"another solution"**:
This new solution does not involve setting the "Read out user data by API" permission.
But when using that solution, we can not display the "short name of the user(Kuerzel)" in the "list Users" of the "supervisor" field, like onOffice Enterprise.
 
image

- Please choose a suitable solution.
Solution 1: Is it possible to always install the "Read out user data by API" permission on the onOffice Enterprise?
=> If feasible, the current solution will still work well

Solution 2: I would use the "get users" API (https://apidoc.onoffice.de/actions/informationen-abfragen/get-users/) and not involve setting the "Read out user data by API" permission.
Note: it will not be possible to display the short name of the user(Kuerzel) in the "select users" list of the "supervisor" field. 

So which solutions that you choose?

**Comment by andernath** [comment]
> @andernath @fredericalpers
> 
> * I found the cause of this bug:
>   In the code, I used this API "https://apidoc.onoffice.de/actions/datensatz-lesen/user/".
>   with the binding conditions:
>   You need read permission to query user data via API. This can be set under “Extras->Einstellungen->Benutzer” / “Extras->Settings->User”. Choose the tab “API user”, then the tab “Rights” with the setting “Benutzerdaten über API auslesen” / “Read out user data by API”.
> * My purpose for using this API:
>   I need to get information "short name of the user(Kuerzel)" to display the "list Users" for the "supervisor" field.
>   => In my opinion, this above bug is because you have not set the "Read out user data by API" permission on onOffice Enterprise.
> * However, we have **"another solution"**:
>   This new solution does not involve setting the "Read out user data by API" permission.
>   But when using that solution, we can not display the "short name of the user(Kuerzel)" in the "list Users" of the "supervisor" field, like onOffice Enterprise.
> 
> image
> 
> * Please choose a suitable solution:
> 
> Solution 1: Is it possible to always install the "Read out user data by API" permission on the onOffice Enterprise? => If feasible, the current solution will still work well
> 
> Solution 2: I would use the "get users" API (https://apidoc.onoffice.de/actions/informationen-abfragen/get-users/) and not involve setting the "Read out user data by API" permission. Note: it will not be possible to display the short name of the user(Kuerzel) in the "select users" list of the "supervisor" field.
> 
> So which solutions that you choose?

Thanks for your investigation @yeneastgate !
I will discuss this with @fredericalpers.

**Comment by fredericalpers** [comment]
@yeneastgate please implement the suggested solution no. 2, without the necessity for the special user rights and displaying the shortname user(Kuerzel). Thank you :)

**Comment by yeneastgate** [comment]
@fredericalpers @andernath I have implemented solution 2. Please take a look at my demo video and help me to review this PR. Thanks! 

https://github.com/onOffice-Web-Org/oo-wp-plugin/assets/104892108/784ffd19-09a2-4c07-8ccd-db894237d235

**Review by andernath — APPROVED** [review]

**Comment by andernath** [comment]
Hi @yeneastgate and @dai-eastgate,
I continued testing and noticed the following:

1. I see no date fields in forms, neither in frontend nor backend. On my enviroment all date fields are text or number inputs.
You can see it here:  
https://w3pm.onofficeweb.com/formulare/formular-test/
I double check if I installed the right version and in the search of estate lists the date and tinyint fields are displayed correctly.
2. I noticed if I deactivate "Betreuer" in Search criteria in Enterprise, I still can choose it in applicant and applicantSearch forms. This should be fixed.
2024-01-15 10_35_17-Window
2024-01-15 10_38_13-Window
4. If I use the search in estate list for a date field, it is empty after my search results are displayed. It should be filled with date I choosed.
5. Also if I use the search in estate list for a tinyint field, and I choose "NO" it will reset to "not specified". It should still be "NO" choosen.
You can see it here:  
https://w3pm.onofficeweb.com/

**Comment by yeneastgate** [comment]
@andernath I will check and let you know soon.

**Comment by yeneastgate** [comment]
@andernath 
> 1. I see no date fields in forms, neither in frontend nor backend. On my enviroment all date fields are text or number inputs.
>    You can see it here:
>    https://w3pm.onofficeweb.com/formulare/formular-test/
>    I double check if I installed the right version and in the search of estate lists the date and tinyint fields are displayed correctly.

The cause of this bug is that the template has been changed so you must copy the template from template.dist/fields.php to folder "onoffice-personalized" and test again



> 2. I noticed if I deactivate "Betreuer/Supervisor" in Search criteria in Enterprise, I still can choose it in applicant and applicantSearch forms. This should be fixed.

Correct, this is a bug. I have fixed it. Below is my video test.

https://github.com/onOffice-Web-Org/oo-wp-plugin/assets/104892108/aa5675f2-605a-48bf-93ad-7ea4efc289e2



> 3\. If I use the search in estate list for a date field, it is empty after my search results are displayed. It should be filled with date I choosed.

I have covered and fixed this bug in PR "https://github.com/onOffice-Web-Org/oo-wp-plugin/pull/694".



> 4\. Also if I use the search in estate list for a tinyint field, and I choose "NO" it will reset to "not specified". It should still be "NO" choosen.

Correct, this is a bug. I have fixed it. Below is my video test.

https://github.com/onOffice-Web-Org/oo-wp-plugin/assets/104892108/4b67b3fd-121e-4ecf-b206-6d91d3185ab1

 Please review this PR for me. Thank!

**Comment by andernath** [comment]
> The cause of this bug is that the template has been changed so you must copy the template from template.dist/fields.php to folder "onoffice-personalized" and test again
> 
@yeneastgate sorry, my mistake. Thanks for your advice. :)

Also thanks for your fixes, I will review and test it again.

**Review by andernath — DISMISSED** [review]

**Comment by andernath** [comment]
@yeneastgate 
I switched to the default template from onOffice plugin. But still most date fields are still not rendered as date inputs. They are still simple text inputs.

For example here you see applicant form (left side) and owner form (right side) with the date field "abdatum" from enterprise.
date_type_in_different_forms_frontend

In Backend the same, date field in applicant (left) is correct, date field in owner (right) is just a simple text field:
date_type_in_different_forms_backend

Current State:

- Date fields of addresses are not rendererd as date fields in all forms
- Date fields of estates are not rendererd as date fields in owner and contact form

Desired State:
All date type fields in all forms are rendererd as date fields.

**Comment by yeneastgate** [comment]
@andernath 
I asked you about this issue before (https://github.com/onOffice-Web-Org/oo-wp-plugin/issues/634#issuecomment-1752725387), but I did not receive a response.
Yes, we will fix it now

**Comment by yeneastgate** [comment]
> Current State:
> 
> * Date fields of addresses are not rendererd as date fields in all forms
> * Date fields of estates are not rendererd as date fields in owner and contact form
> 
> Desired State: All date type fields in all forms are rendererd as date fields.

@andernath I fixed it. Please watch my video demo and let me know your opinions. Thanks!

https://github.com/onOffice-Web-Org/oo-wp-plugin/assets/104892108/decc9d74-19f7-450e-bf39-8340edea8b9d

**Comment by andernath** [comment]
> @andernath I asked you about this issue before ([#634 (comment)](https://github.com/onOffice-Web-Org/oo-wp-plugin/issues/634#issuecomment-1752725387)), but I did not receive a response. Yes, we will fix it now

I'm very sorry @yeneastgate @fredericalpers and I missed your comment :/

The video looks good. I will check code and start testing soon. Thank you!

**Review by andernath — APPROVED** [review]

**Pull request merged**
