### PR TITLE
48659 Optional writing of tasks in onOffice enterprise with plugin forms & fields.

### PR DESCRIPTION
**Pull request by yeneastgate**
related to https://github.com/onOffice-Web-Org/oo-wp-plugin/issues/820
changed log:
Add task option & create task when create forms

### CODE REVIEW

**Comment by fredericalpers** [comment]
@yeneastgate Thank you for the work so far! The task creation functionality from the forms is working well. However, there are a few outstanding issues that need to be addressed:

**Missing Task Type "Callback":**
The task type "Callback" is not yet available. This needs to be added to ensure that users can select this type when creating tasks. Please implement this as part of the task creation process.

**Field Enable/Disable Logic:**
Currently, the fields related to task creation should be disabled when the checkbox for creating tasks is not selected. However, it appears that this logic isn't functioning as expected. When the checkbox is unchecked, all other fields should be disabled to prevent any accidental input. Please update the UI to reflect this behavior.

**Linking Tasks to Incoming Emails:**
To provide better context for tasks, they should be linked to the incoming emails from which they originate. This can be achieved by using the mailMessageId parameter, which allows the task to be associated with the specific email. Refer to the [onOffice API documentation for more details](https://apidoc.onoffice.de/actions/datensatz-anlegen/tasks/) on how to implement this. Ensuring that tasks are properly linked to emails will improve traceability and context.

Once these issues are addressed, the feature will be much closer to completion. Please make the necessary adjustments and let me know if you have any questions. Thanks again for your efforts

**Comment by yeneastgate** [comment]
@fredericalpers I will check it.

**Comment by fredericalpers** [comment]
@yeneastgate please ignore the connection to the email.

For now only check the field enable/disable logic which also needs implementation in #821 

Thank you :)

**Comment by fredericalpers** [comment]
Vorgezogen auf 5.2

**Comment by yeneastgate** [comment]
> **Missing Task Type "Callback":**
> The task type "Callback" is not yet available. This needs to be added to ensure that users can select this type when creating tasks. Please implement this as part of the task creation process.

@fredericalpers I found that the "callback" API with the key "Rückruf" currently does not return a label. Can you check with the IT department? Otherwise, we will hard code it, but it will not be translatable.

image

**Comment by fredericalpers** [comment]
> > **Missing Task Type "Callback":**
> > The task type "Callback" is not yet available. This needs to be added to ensure that users can select this type when creating tasks. Please implement this as part of the task creation process.
> 
> @fredericalpers I found that the "callback" API with the key "Rückruf" currently does not return a label. Can you check with the IT department? Otherwise, we will hard code it, but it will not be translatable.


@yeneastgate please hard code it for now, using a onOffice Textkey, then we should be able to translate it in WordPress. Thank you. :)

**Comment by yeneastgate** [comment]
@fredericalpers I got it.

**Comment by yeneastgate** [comment]
> **Missing Task Type "Callback":**
> The task type "Callback" is not yet available. This needs to be added to ensure that users can select this type when creating tasks. Please implement this as part of the task creation process.

@fredericalpers I fixed it. Please take a look at my video and let me know your opinions. Thanks!

https://github.com/user-attachments/assets/2b0e0b6d-69a7-41f7-b47a-257dacdc6674

**Comment by fredericalpers** [comment]
@dai-eastgate It appears that there are merge conflicts in this branch that need to be resolved before we can proceed with the merge. Please resolve the conflicts in the affected files and update the branch. Thank you in advance :)

**Review by andernath — APPROVED** [review]

**Pull request merged**
