### PR TITLE
54192 Map for address list with pin display and show/hide functionality

### PR DESCRIPTION
**Pull request by yeneastgate**
related to https://github.com/onOffice-Web-Org/oo-wp-plugin/issues/948
changed log:

### CODE REVIEW

**Comment by fredericalpers** [comment]
Hi @yeneastgate I tested the feature, and unfortunately, it's currently not working as expected. When trying to activate the feature, an error message appears, and the changes cannot be saved.

Could you please take another look?

Error: There was a problem saving the view. Please make sure that the name of the view is unique, even across all address list types.

error1234

**Comment by yeneastgate** [comment]
@fredericalpers Could you please try downgrading the plugin version to 55 to check again? The issue seems to occur only when the wp_oo_plugin_listviews_address table has not been updated.


Uploading 54192-downgrade-version.mp4…

**Comment by yeneastgate** [comment]
@fredericalpers Could you please try downgrading the plugin version to 55 to check again? The issue seems to occur only when the wp_oo_plugin_listviews_address table has not been updated.


https://github.com/user-attachments/assets/62736e14-0f62-41cd-9a96-7f5e1f4b732d

**Review by miauzjpg — CHANGES_REQUESTED** [review]

**Review by miauzjpg — APPROVED** [review]

**Review by miauzjpg — APPROVED** [review]
great!

**Pull request merged**
